assert_raise(${1:Exception}) { ${2} }
